DROP TABLE LIKES;
DROP TABLE BOOKMARK;
DROP TABLE REPLY;
DROP TABLE ATTACHMENT;
DROP TABLE REPORT;
DROP TABLE QNA;
DROP TABLE TODAY;
DROP TABLE NOTICE;
DROP TABLE BOARD;
DROP TABLE CATEGORY;
DROP TABLE MT_INFO;
DROP TABLE MEMBER;
DROP TABLE GRADE;


DROP SEQUENCE SEQ_RPLNO;
DROP SEQUENCE SEQ_FNO;
DROP SEQUENCE SEQ_REPNO;
DROP SEQUENCE SEQ_QNO;
DROP SEQUENCE SEQ_TNO;
DROP SEQUENCE SEQ_BNO;
DROP SEQUENCE SEQ_MNO;
DROP SEQUENCE SEQ_NNO;

---- 등급(등력) ------

CREATE TABLE GRADE(
    GRADE_NO NUMBER CONSTRAINT GRADENO_PK PRIMARY KEY,
    GRADE_NAME VARCHAR2(20) CONSTRAINT GRADENAME_NN NOT NULL
);

COMMENT ON COLUMN GRADE.GRADE_NO IS '등력번호';
COMMENT ON COLUMN GRADE.GRADE_NAME IS '등력명칭';

INSERT INTO GRADE (GRADE_NO, GRADE_NAME) VALUES (10, '등린이');
INSERT INTO GRADE (GRADE_NO, GRADE_NAME) VALUES (20, '등산매니아');
INSERT INTO GRADE (GRADE_NO, GRADE_NAME) VALUES (30, '엄홍길');
INSERT INTO GRADE (GRADE_NO, GRADE_NAME) VALUES (40, '산신령');

----- 게시판 카테고리 ------

CREATE TABLE CATEGORY(
    CATEGORY_NO NUMBER CONSTRAINT CATENO_PK PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(20) CONSTRAINT CATENAME_NN NOT NULL
);

COMMENT ON COLUMN CATEGORY.CATEGORY_NO IS '카테고리번호';
COMMENT ON COLUMN CATEGORY.CATEGORY_NAME IS '카테고리이름';

INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (10, '일상');
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (20, '자유');
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (30, '질문');

-------- 사용자 -------------------

CREATE TABLE MEMBER(
    USER_NO NUMBER CONSTRAINT USER_NO_PK PRIMARY KEY,
    USER_ID VARCHAR2(20) NOT NULL UNIQUE,
    USER_PWD VARCHAR2(20) NOT NULL,
    USER_NAME VARCHAR2(20) NOT NULL,
    NICKNAME VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(20) NOT NULL,
    GENDER VARCHAR2(1),
    PHONE VARCHAR2(20) NOT NULL,
    DESCRIPTION VARCHAR2(100),
    PROFILE_IMG VARCHAR2(1000),
    GRADE_NO NUMBER NOT NULL,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')) NOT NULL,
    COMPLETE_MT VARCHAR2(2000) NULL,
    INSTA_ID VARCHAR2(30),
    FOREIGN KEY(GRADE_NO) REFERENCES GRADE(GRADE_NO)
    );

COMMENT ON COLUMN MEMBER.USER_NO IS '유저번호';
COMMENT ON COLUMN MEMBER.USER_ID IS '아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.USER_NAME IS '이름';
COMMENT ON COLUMN MEMBER.NICKNAME IS '닉네임';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.GENDER IS '성별';
COMMENT ON COLUMN MEMBER.PHONE IS '휴대폰';
COMMENT ON COLUMN MEMBER.DESCRIPTION IS '한줄소개';
COMMENT ON COLUMN MEMBER.PROFILE_IMG IS '프로필사진';
COMMENT ON COLUMN MEMBER.GRADE_NO IS '등력';
COMMENT ON COLUMN MEMBER.STATUS IS '상태값';
COMMENT ON COLUMN MEMBER.COMPLETE_MT IS '등반완료산';


CREATE SEQUENCE SEQ_MNO NOCACHE;


INSERT INTO MEMBER (
    USER_NO, USER_ID, USER_PWD, USER_NAME, NICKNAME, EMAIL, GENDER, PHONE, DESCRIPTION, PROFILE_IMG, GRADE_NO, STATUS, COMPLETE_MT
) VALUES (
    SEQ_MNO.NEXTVAL, 'admin', '1234', '관리자', '관리자', 'admin@example.com', 'M', '010-123-4567', '', 'profile2.jpg', 10, DEFAULT, NULL
);

INSERT INTO MEMBER (
    USER_NO, USER_ID, USER_PWD, USER_NAME, NICKNAME, EMAIL, GENDER, PHONE, DESCRIPTION, PROFILE_IMG, GRADE_NO, STATUS, COMPLETE_MT
) VALUES (
    SEQ_MNO.NEXTVAL, 'user01', 'pass01', '차은우', '초보등산러', 'user01@example.com', 'M', '010-456-7890', '안녕하세요 등린이 차은우입니다.', 'profile1.jpg', 20, DEFAULT, NULL
);

INSERT INTO MEMBER (
    USER_NO, USER_ID, USER_PWD, USER_NAME, NICKNAME, EMAIL, GENDER, PHONE, DESCRIPTION, PROFILE_IMG, GRADE_NO, STATUS, COMPLETE_MT
) VALUES (
    SEQ_MNO.NEXTVAL, 'user02', 'pass02', '장원영', '등산딱대', '10pretty@example.com', 'F', '010-654-3210', '제 프로필에 방문해주셔서 감사링~^^', 'profile2.jpg', 30, DEFAULT, NULL
);



--------- BOARD -----------

CREATE TABLE BOARD(
    BOARD_NO VARCHAR2(5) CONSTRAINT BNO_PK PRIMARY KEY,
    BOARD_TITLE VARCHAR2(100) CONSTRAINT BTITLE_NN NOT NULL,
    BOARD_CONTENT VARCHAR2(4000) CONSTRAINT BCONTENT_NN NOT NULL,
    HASHTAG VARCHAR2(100),
    COUNT NUMBER DEFAULT 0,
    BOARD_WRITER NUMBER CONSTRAINT BWRITER_NN NOT NULL,
    CATEGORY_NO NUMBER CONSTRAINT BCATEGORYNO_NN NOT NULL,
    BOARD_TYPE NUMBER CONSTRAINT BTYPE_NN NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    FOREIGN KEY (BOARD_WRITER) REFERENCES MEMBER(USER_NO),
    FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY(CATEGORY_NO)
);

COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글번호';
COMMENT ON COLUMN BOARD.BOARD_TYPE IS '게시글타입(자유1/에디터스픽2)';
COMMENT ON COLUMN BOARD.CATEGORY_NO IS '카테고리번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글내용';
COMMENT ON COLUMN BOARD.BOARD_WRITER IS '작성자회원번호';
COMMENT ON COLUMN BOARD.COUNT IS '조회수';
COMMENT ON COLUMN BOARD.CREATE_DATE IS '작성일';
COMMENT ON COLUMN BOARD.STATUS IS '상태값(Y/N)';
COMMENT ON COLUMN BOARD.HASHTAG IS '해시태그';

CREATE SEQUENCE SEQ_BNO
NOCACHE;

INSERT INTO BOARD
VALUES ('B' || SEQ_BNO.NEXTVAL, '첫번째 게시글 - 오늘 하루 일상', '첫번째 게시글입니다 ', '#FIRST', DEFAULT, 1, 10, 1, '2023-08-18', DEFAULT);

INSERT INTO BOARD
VALUES ('B' || SEQ_BNO.NEXTVAL, '두번째 게시글 - 자유글', '두번째 게시글입니다 ', NULL, DEFAULT, 2, 20, 1, DEFAULT, DEFAULT);

INSERT INTO BOARD
VALUES ('B' || SEQ_BNO.NEXTVAL, '세번째 게시글 - 질문글', '세번째 게시글입니다 ', NULL, DEFAULT, 3, 30, 1, DEFAULT, DEFAULT);


----  첨부파일  -----

----  첨부파일  -----

CREATE TABLE ATTACHMENT(
   FILE_NO NUMBER CONSTRAINT FILE_NO_PK PRIMARY KEY,
   REF_NO VARCHAR2(5) NOT NULL,
   ORIGIN_NAME VARCHAR2(255) NOT NULL,
   CHANGE_NAME VARCHAR2(255) NOT NULL,
   FILE_PATH VARCHAR2(1000) NOT NULL,
   UPLOAD_DATE DATE DEFAULT SYSDATE,
   FILE_LEVEL NUMBER NOT NULL,
   STATUS VARCHAR2(1) DEFAULT 'Y'
);

COMMENT ON COLUMN ATTACHMENT.FILE_NO IS '파일번호';
COMMENT ON COLUMN ATTACHMENT.REF_NO IS '참조게시글번호';
COMMENT ON COLUMN ATTACHMENT.ORIGIN_NAME IS '파일원본명';
COMMENT ON COLUMN ATTACHMENT.CHANGE_NAME IS '파일수정명';
COMMENT ON COLUMN ATTACHMENT.FILE_PATH IS '저장폴더경로';
COMMENT ON COLUMN ATTACHMENT.UPLOAD_DATE IS '업로드일';
COMMENT ON COLUMN ATTACHMENT.FILE_LEVEL IS '파일레벨';
COMMENT ON COLUMN ATTACHMENT.STATUS IS '상태값';

CREATE SEQUENCE SEQ_FNO NOCACHE; 

------  게시글 신고  --------
CREATE TABLE REPORT(
   REPORT_NO NUMBER CONSTRAINT NO_PK PRIMARY KEY,
   GUILTY VARCHAR2(100),
   REPORT_CONTENT VARCHAR2(1000) NOT NULL,
   PROCESS CHAR(1) DEFAULT 'N',
   TYPE VARCHAR2(100),
   BOARD_NO VARCHAR2(5) NOT NULL,
   REPORT_UNO NUMBER NOT NULL,
   REPORTED_UNO NUMBER NOT NULL,
   FOREIGN KEY (BOARD_NO) REFERENCES BOARD,
   FOREIGN KEY (REPORT_UNO) REFERENCES MEMBER,
   FOREIGN KEY (REPORTED_UNO) REFERENCES MEMBER
);

COMMENT ON COLUMN REPORT.REPORT_NO IS '신고번호';
COMMENT ON COLUMN REPORT.GUILTY IS '혐의';
COMMENT ON COLUMN REPORT.REPORT_CONTENT IS '내용';
COMMENT ON COLUMN REPORT.PROCESS IS '처리여부';
COMMENT ON COLUMN REPORT.TYPE IS '게시글타입';
COMMENT ON COLUMN REPORT.BOARD_NO IS '게시글번호';
COMMENT ON COLUMN REPORT.REPORT_UNO IS '신고한사람';
COMMENT ON COLUMN REPORT.REPORTED_UNO IS '신고받은사람';

CREATE SEQUENCE SEQ_REPNO NOCACHE;


-- 북마크 ---

CREATE TABLE BOOKMARK (
   USER_NO NUMBER,
   BOARD_NO VARCHAR2(5),
   FOREIGN KEY (BOARD_NO) REFERENCES BOARD,
   FOREIGN KEY (USER_NO) REFERENCES MEMBER,
   PRIMARY KEY (BOARD_NO, USER_NO)
);

COMMENT ON COLUMN BOOKMARK.BOARD_NO IS '게시글번호';
COMMENT ON COLUMN BOOKMARK.USER_NO IS '유저번호';


INSERT INTO BOOKMARK
VALUES(1, 'B1');

INSERT INTO BOOKMARK
VALUES(2, 'B2');

INSERT INTO BOOKMARK
VALUES(3, 'B3');


---- 좋아요  ----

CREATE TABLE LIKES (
   USER_NO NUMBER,
   BOARD_NO VARCHAR2(5),
   FOREIGN KEY (BOARD_NO) REFERENCES BOARD,
   FOREIGN KEY (USER_NO) REFERENCES MEMBER,
   PRIMARY KEY(USER_NO, BOARD_NO)
);

COMMENT ON COLUMN LIKES.USER_NO IS '유저번호';
COMMENT ON COLUMN LIKES.BOARD_NO IS '게시글번호';

INSERT INTO LIKES
VALUES (1, 'B1');

INSERT INTO LIKES
VALUES (2, 'B2');

INSERT INTO LIKES
VALUES (2, 'B3');




---- 댓글 -----


CREATE TABLE REPLY (
   REPLY_NO NUMBER CONSTRAINT REPLY_NO_PK PRIMARY KEY,
   REPLY_CONTENT VARCHAR2(400) NOT NULL,
   CREATE_DATE   DATE DEFAULT SYSDATE,
   STATUS VARCHAR2(1) DEFAULT 'Y',
   REF_BNO VARCHAR2(5) NOT NULL,
   REPLY_WRITER NUMBER NOT NULL,
   FOREIGN KEY (REPLY_WRITER) REFERENCES MEMBER,
   FOREIGN KEY (REF_BNO) REFERENCES BOARD
);

COMMENT ON COLUMN REPLY.REPLY_NO IS '댓글번호';
COMMENT ON COLUMN REPLY.REPLY_CONTENT IS '댓글내용';
COMMENT ON COLUMN REPLY.CREATE_DATE IS '작성일';
COMMENT ON COLUMN REPLY.STATUS IS '상태값';
COMMENT ON COLUMN REPLY.REF_BNO IS '참조게시글번호';
COMMENT ON COLUMN REPLY.REPLY_WRITER IS '작성자유저번호';

CREATE SEQUENCE SEQ_RPLNO NOCACHE; 

INSERT INTO REPLY
VALUES(SEQ_RPLNO.NEXTVAL, '너무 좋아요', DEFAULT, DEFAULT, 'B1', 2);

INSERT INTO REPLY
VALUES(SEQ_RPLNO.NEXTVAL, '저도 다음에 가고 싶어요', DEFAULT, DEFAULT, 'B2', 3);

INSERT INTO REPLY
VALUES(SEQ_RPLNO.NEXTVAL,  '풍경이 좋네요', DEFAULT, DEFAULT, 'B1', 3);


-----  공지사항 -----

CREATE TABLE NOTICE(
    NOTICE_NO VARCHAR2(5) CONSTRAINT NOTI_NO_PK PRIMARY KEY,
    NOTICE_TITLE VARCHAR2(100) NOT NULL,
    NOTICE_CONTENT VARCHAR2(4000) NOT NULL,
    COUNT NUMBER DEFAULT 1,
    CREATE_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(1) DEFAULT 'Y',
    NOTICE_WRITER NUMBER NOT NULL,
    FOREIGN KEY (NOTICE_WRITER) REFERENCES MEMBER(USER_NO)
    );

COMMENT ON COLUMN NOTICE.NOTICE_NO IS '공지사항번호';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '공지사항제목';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '공지사항내용';
COMMENT ON COLUMN NOTICE.COUNT IS '조회수';
COMMENT ON COLUMN NOTICE.CREATE_DATE IS '작성일';
COMMENT ON COLUMN NOTICE.STATUS IS '상태값';
COMMENT ON COLUMN NOTICE.NOTICE_WRITER IS '작성자유저번호';


CREATE SEQUENCE SEQ_NNO NOCACHE;


INSERT INTO NOTICE (
    NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_WRITER
) VALUES (
    'N' || SEQ_NNO.NEXTVAL, '중요 업데이트 사안입니다.', '사용자들에게 편리한 서비스를 제공하기 위해 대규모 업데이트가 진행되었습니다...', 1
);

INSERT INTO NOTICE (
    NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_WRITER
) VALUES (
    'N' || SEQ_NNO.NEXTVAL, 'MOUNTINEER 커뮤니티 가이드라인', '커뮤니티 가이드라인 입니다. 모두 즐거운 등산하시길 바랍니다.', 2
);

INSERT INTO NOTICE (
    NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_WRITER
) VALUES (
   'N' ||  SEQ_NNO.NEXTVAL, '오등완 게시판 업데이트', '오등완 게시판을 새롭게 단장하였습니다. 티니어 여러분들의 많은 사용 부탁드립니다!', 3
);


---------------오등완 게시판 관련-------------
CREATE TABLE TODAY(
  TODAY_NO VARCHAR2(5) CONSTRAINT TODAY_NO_PK NOT NULL PRIMARY KEY,               
  TODAY_TITLE VARCHAR2(100) NOT NULL ,   
  TODAY_CONTENT VARCHAR2(4000) NOT NULL,  
  TODAY_TIP VARCHAR2(1000),  
  HASHTAG VARCHAR2(100),              
  TODAY_NAME VARCHAR2(20),            
  TODAY_DATE DATE NOT NULL,
  TODAY_TIME NUMBER NOT NULL,
  TODAY_COURSE VARCHAR2(100),
  LEV VARCHAR2(20),
  TODAY_VEHICLE VARCHAR2(30),
  TODAY_WRITER NUMBER NOT NULL,
  TODAY_TYPE NUMBER,
  FOREIGN KEY(TODAY_WRITER) REFERENCES MEMBER(USER_NO)
);
-- LEVEL 예약어라 LEV으로 수정함

CREATE SEQUENCE SEQ_TNO
NOCACHE;

COMMENT ON COLUMN TODAY.TODAY_NO IS '게시글번호';
COMMENT ON COLUMN TODAY.TODAY_TITLE IS '제목';
COMMENT ON COLUMN TODAY.TODAY_CONTENT IS '내용';
COMMENT ON COLUMN TODAY.TODAY_TIP IS '하이킹팁';
COMMENT ON COLUMN TODAY.HASHTAG IS '해시태그';
COMMENT ON COLUMN TODAY.TODAY_NAME IS '산이름';
COMMENT ON COLUMN TODAY.TODAY_DATE IS '등산일자';
COMMENT ON COLUMN TODAY.TODAY_TIME IS '소요시간';
COMMENT ON COLUMN TODAY.TODAY_COURSE IS '코스이름';
COMMENT ON COLUMN TODAY.LEV IS '레벨';
COMMENT ON COLUMN TODAY.TODAY_VEHICLE IS '교통';
COMMENT ON COLUMN TODAY.TODAY_TYPE IS '게시판타입';

INSERT INTO TODAY
VALUES ('T' || SEQ_TNO.NEXTVAL, '울릉포 깃대봉 다녀왔어요', '소문답게 뷰가 너무 이뻐요', '성인봉보다 깃대봉 뷰 보세요','#울릉도', '깃대봉','2023/08/10', 1,'깃대봉코스', '쉬움', '배', 1,2);

INSERT INTO TODAY
VALUES ('T' || SEQ_TNO.NEXTVAL, '장마시작 전 한라산', '평일인데도 사람이 제법 많았어요.', '두 눈 가득 펼쳐지는 제주도', '#제주도', '한라산', '2023/08/15', 2, '진달래대피소코스', '보통', '비행기',2,1);

INSERT INTO TODAY
VALUES ('T' || SEQ_TNO.NEXTVAL, '불암산 4코스 등반!', '중간 중간 쉴 수 있는 공간이 많아서 좋았어요! ', '4코스는 암릉길이 많아 장갑과 등산화는 필수!', '#불암산', '불암산', '2023/08/20', 3, '정암사코스', '쉬움', '대중교통',3,3);




---------- QNA ----------

CREATE TABLE QNA(
  Q_NO VARCHAR2(5) CONSTRAINT QNO_PK PRIMARY KEY,
  Q_TITLE VARCHAR2(100) CONSTRAINT QTITLE_NN NOT NULL,
  Q_CONTENT VARCHAR2(4000) CONSTRAINT QCONTENT_NN NOT NULL,
  Q_WRITER NUMBER CONSTRAINT QWRITER_NN NOT NULL,
  Q_DATE DATE DEFAULT SYSDATE NOT NULL,
  COUNT NUMBER DEFAULT 0, 
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
  FOREIGN KEY(Q_WRITER) REFERENCES MEMBER(USER_NO)
);

COMMENT ON COLUMN QNA.Q_NO IS '문의글번호';
COMMENT ON COLUMN QNA.Q_TITLE IS '문의글제목';
COMMENT ON COLUMN QNA.Q_CONTENT IS '문의글내용';
COMMENT ON COLUMN QNA.Q_WRITER IS '작성자회원번호';
COMMENT ON COLUMN QNA.Q_DATE IS '작성일';
COMMENT ON COLUMN QNA.COUNT IS '조회수';
COMMENT ON COLUMN QNA.STATUS IS '상태값(Y/N)';

CREATE SEQUENCE SEQ_QNO
NOCACHE;

INSERT INTO QNA
VALUES (SEQ_QNO.NEXTVAL, '첫번째 질문글입니다.', '첫번째 질문글 내용입니다.', 2, '2023-08-18', 0, DEFAULT);

INSERT INTO QNA
VALUES (SEQ_QNO.NEXTVAL, '두번째 질문글입니다.', '두번째 질문글 내용입니다.', 2, '2023-08-20', 0, DEFAULT);

INSERT INTO QNA
VALUES (SEQ_QNO.NEXTVAL, '세번째 질문글입니다.', '세번째 질문글 내용입니다.', 3, '2023-08-21', 0, DEFAULT);


CREATE TABLE MT_INFO(
    MT_NAME VARCHAR2(20) CONSTRAINT MT_NAME_PK PRIMARY KEY,
    MT_ADDRESS VARCHAR2(200) CONSTRAINT MT_ADDRESS_NN NOT NULL ,
    MT_PHONE VARCHAR2(20) NULL ,
    MT_PAGE VARCHAR2(100) NULL ,
    MT_COURSE VARCHAR2(1000) NULL,
    MT_VEHICLE VARCHAR2(2000) NULL,
    MT_DETAILINFO VARCHAR2(4000),
    MT_DETAILADDRESS VARCHAR2(4000)
    );

COMMENT ON COLUMN MT_INFO.MT_NAME IS '산이름';
COMMENT ON COLUMN MT_INFO.MT_ADDRESS IS '주소';
COMMENT ON COLUMN MT_INFO.MT_PHONE IS '전화번호';
COMMENT ON COLUMN MT_INFO.MT_PAGE IS '홈페이지';
COMMENT ON COLUMN MT_INFO.MT_COURSE IS '코스';
COMMENT ON COLUMN MT_INFO.MT_VEHICLE IS '교통';
COMMENT ON COLUMN MT_INFO.MT_DETAILINFO IS '산상세정보';
COMMENT ON COLUMN MT_INFO.MT_DETAILADDRESS IS '산상세주소';

COMMIT;


     SELECT 
            Q_NO
            , Q_TITLE
            , Q_CONTENT
            , TO_CHAR(Q_DATE, 'YYYY/MM/DD') "QNA_DATE"
        FROM QNA 
        JOIN MEMBER ON (Q_WRITER = USER_NO)
        WHERE Q_NO = 'Q'||'?'
        ;
        
         	UPDATE
       	QNA
     SET COUNT = COUNT + 1
    WHERE Q_NO = ?
    ;
    
    UPDATE QNA
          SET STATUS = 'N'
          WHERE NOTICE_NO = ?
    
    ;


SELECT *
FROM (
    SELECT ROWNUM RNUM, A.*
    FROM (
        SELECT
            Q_NO,
            Q_TITLE,
            Q_CONTENT,
            TO_CHAR(Q_DATE, 'YYYY/MM/DD') AS "QNA_DATE"
        FROM QNA Q
        JOIN MEMBER M ON (Q.Q_WRITER = M.USER_NO)
        WHERE Q.STATUS = 'Y'
        ORDER BY Q.Q_NO DESC
    ) A
)



